FROM registry.access.redhat.com/ubi9:latest AS builder


RUN dnf install -y cargo openssl-devel \
    && cargo install mdbook --locked \
    && cargo install mdbook-callouts \
    && cargo install mdbook-mermaid \
    && cargo install mdbook-kroki-preprocessor --locked


FROM registry.access.redhat.com/ubi9:latest

COPY --from=builder /root/.cargo/bin/mdbook /usr/bin
COPY --from=builder /root/.cargo/bin/mdbook-callouts /usr/bin
COPY --from=builder /root/.cargo/bin/mdbook-mermaid /usr/bin
COPY --from=builder /root/.cargo/bin/mdbook-kroki-preprocessor /usr/bin/mdbook-kroki

RUN mkdir -p /workspace
VOLUME /workspace
WORKDIR /workspace

ENTRYPOINT ["/usr/bin/mdbook"]
